networks:
    skynet:

services:
    mvc:
        build:
            context: Project2/Project2.Client
            dockerfile: ../../.docker/client.dockerfile
        image: gazawayj/clientproj
        ports:
            - 9000:80 
        networks:
            - skynet

    service_1:
        build:
            context: Project2/Project2.GridService
            dockerfile: ../../.docker/grid.dockerfile
        image: gazawayj/gridproj
        ports:
            - 8000:80 
        networks:
            - skynet
        environment:
            ConnectionStrings__main: "server=sql_1;database=GridServiceDb;user id=sa;password=Password12345" 

    sql_1:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password12345
        networks:
            - skynet
        ports:
            - 1433:1433 
            
    service_2:
        build:
            context: Project2/Project2.UserService
            dockerfile: ../../.docker/user.dockerfile
        image: gazawayj/userproj
        ports:
            - 7000:80 
        networks:
            - skynet
        environment:
            ConnectionStrings__main: "server=sql_2;database=UserServiceDb;user id=sa;password=Password12345"  

    sql_2:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password12345
        networks:
            - skynet
        ports:
            - 1434:1433
            #TODO: port 1433:1433


version: "3.7"