networks:
    skynet:
  
services:
    mvc:
        build:
            context: Project2/Project2.Client
            dockerfile: ../../.docker/client.dockerfile
        image: rst929/clientproj
        ports:
            - 9000:80 # will break
        networks:
            - skynet

    service_1:
        build:
            context: Project2/Project2.GridService
            dockerfile: ../../.docker/grid.dockerfile
        image: rst929/gridserviceproj
        ports:
            - 8000:80 # will break
        networks:
            - skynet
        environment:
            ConnectionStrings__main: "server=sql;database=PizzaBoxDb;user id=sa;password=Password12345" # need new database?

    sql_1:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password12345
        networks:
            - skynet
        ports:
            - 1433:1433 # maybe will break
            
    service_2:
        build:
            context: Project2/Project2.UserService
            dockerfile: ../../.docker/user.dockerfile
        image: rst929/userserviceproj
        ports:
            - 7000:80 # will break
        networks:
            - skynet
        environment:
            ConnectionStrings__main: "server=sql;database=PizzaBoxDb;user id=sa;password=Password12345"  #need new database?

    # second sql? Will probably also break
    sql_2:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password12345
        networks:
            - skynet
        ports:
            - 1433:1433 # maybe will break
        
version: "3.7"