// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project2.UserService.Storage;

namespace Project2.UserService.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20200406192032_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project2.UserService.Models.UserModel", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("UserModels");

                    b.HasData(
                        new
                        {
                            Username = "Randall1",
                            EmailAddress = "randall@email.com",
                            FirstName = "Randall",
                            LastName = "Steinkamp",
                            Password = "password"
                        },
                        new
                        {
                            Username = "Jim1",
                            EmailAddress = "jim@email.com",
                            FirstName = "Jim",
                            LastName = "Gazaway",
                            Password = "password"
                        },
                        new
                        {
                            Username = "Bianca1",
                            EmailAddress = "bianca@email.com",
                            FirstName = "Bianca",
                            LastName = "Visconti",
                            Password = "password"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
