// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project2.GridService.Storage;

namespace Project2.GridService.Migrations
{
    [DbContext(typeof(GridDbContext))]
    partial class GridDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project2.GridService.Model.GridModel", b =>
                {
                    b.Property<long>("GridModelId")
                        .HasColumnType("bigint");

                    b.Property<string>("GridModelInfo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GridModelId");

                    b.ToTable("GridModels");
                });
#pragma warning restore 612, 618
        }
    }
}
